import type { Catalog } from '@/features/catalog-site/types';
import { CATALOG_PAGES } from './pages';

export const CATALOG: Catalog = {
  id: 'spectra-plast',
  name: 'Catalog & Website',
  companyName: 'Spectra Plast Pvt. Ltd.',
  siteUrl: 'www.pepagora.com/autogenerated_site',
  pages: CATALOG_PAGES,
  plan: {
    name: 'Scale',
    price: '$960',
    term: 'Paid Yearly',
    nextBilling: '20th Aug 2026',
  },
  // Values come from the mobile design; swap for the API when it exists.
  analytics: {
    views: 100,
    lastEdited: '12-05-2025',
    lastEditedBy: 'John',
    status: 'Active',
  },
};

export const FOOTER_LINKS = {
  company: [
    'About Us',
    'Infrastructure',
    'Quality Assurance',
    'Team',
    'Contact us',
  ],
  productGroups: Array.from({ length: 3 }, (_, col) =>
    Array.from({ length: 3 }, (_, row) => ({
      id: `group-${col}-${row}`,
      title: `Group${row + 1}`,
      items: [
        'Mini Vertical Band Sealing Machine',
        'Horizontal Band Sealer – Stainless',
      ],
    })),
  ),
};

/** Catalog site navigation. `hasMenu` renders the dropdown caret. */
export const SITE_NAV = [
  { label: 'Home', hasMenu: false },
  { label: 'About us', hasMenu: true },
  { label: 'Products', hasMenu: true },
  { label: 'Contact', hasMenu: false },
];
