export type IconName =
  // app chrome
  | 'menu'
  | 'search'
  | 'mic'
  | 'image'
  | 'globe'
  | 'bell'
  | 'user'
  | 'chevron-down'
  | 'chevron-up'
  | 'chevron-left'
  | 'chevron-right'
  | 'arrow-left'
  | 'arrow-right'
  | 'plus'
  | 'close'
  | 'filter'
  | 'pencil'
  | 'play'
  | 'eye'
  | 'settings'
  | 'panel'
  | 'upload'
  // left rail
  | 'home'
  | 'messages'
  | 'analytics'
  | 'catalog'
  | 'reports'
  | 'sourcing'
  | 'trends'
  | 'profile'
  | 'media'
  | 'support'
  // site content
  | 'shield-user'
  | 'building'
  | 'clock'
  | 'briefcase'
  | 'cash'
  | 'transfer'
  | 'expand'
  | 'users'
  | 'box'
  | 'star'
  | 'quote'
  | 'chat'
  | 'mail'
  | 'phone'
  | 'pin'
  | 'lock'
  | 'linkedin'
  | 'instagram'
  | 'facebook'
  | 'youtube'
  // industries
  | 'agriculture'
  | 'manufacturing'
  | 'construction'
  | 'infrastructure'
  | 'logistics'
  | 'cement'
  | 'piping'
  | 'food';

export interface IconProps extends React.SVGProps<SVGSVGElement> {
  name: IconName;
  size?: number;
}
